version: 2

models:
  - name: fact_sales
    description: "Fact table for item."
    columns:
      - name: invoice_and_item_number
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: store_number
        description: "The foreign key to the store dimension table"
        tests:
          - relationships:
              # Uncomment the line 'arguments:' to resolve
              # MissingArgumentsPropertyInGenericTestDeprecation Warnings
              # Warnings appear Python 3.11 environment
              # 'arguments:' will not work in older versions of dbt (Python 3.10 and below)
              #arguments:
                to: ref('dim_store')
                field: store_number
